### ISSUE TITLE
Config option to change the name of the plugin sending the message to the player not there.

### ISSUE THREAD

**Issue by KiriCattus** [ModdedMinecraft/MMCRules-Sponge#1]
I have looked into the code and found that when my config generated the option to change the bots name was not there so it defaults to MMCRules.

Could you fix this for the next release please as I was looking for this plugin about 12 hours before you uploaded your plugin to Ore and it has been great so far :)

All the best!

Proxy

**Comment by leelawd** [comment]
Oops, i will fix that soon :)
