### ISSUE TITLE
no commands

### ISSUE THREAD

**Issue by FirEmerald** [ModdedMinecraft/MMCRules-Sponge#2]
on my spongeforge server, there are no commands from this mod, and the mod doesn't prevent the player from performing actions regardless of config settings. (Version 1.1, going to test other versions soon)

**Comment by leelawd** [comment]
Could you post a plugins list?

**Comment by FirEmerald** [comment]
plugins:
Anti-WorldDownload
Economy Lite
Grief Prevention
LuckPerms (I gave myself access to all permission nodes)
Mailboxes
MMCRules (of course)
Player Shops RPG
React

mods:
Mantle
Tinker's Construct
SpongeForge

I know the plugin is active because I get the login message

**Comment by FirEmerald** [comment]
no luck with 1.0.2.

**Comment by FirEmerald** [comment]
Is it possible that using the 5.2.0 API is making these features not work? I can't go back to 5.0.0 so if that's the case I'll either wait for an update or remove the plugin.

**Comment by leelawd** [comment]
After im finished a few things, ill get to testing this. I dont think its the API as i run 5.2.0 on my own servers with this

**Comment by leelawd** [comment]
Do you have a FML log i could see?

**Comment by FirEmerald** [comment]
[fml-server-latest.zip](https://github.com/ModdedMinecraft/MMCRules-Sponge/files/822786/fml-server-latest.zip)

**Comment by leelawd** [comment]
I see the problem. "List should have ended with ] or had a comma, instead had token: '!' (Reserved character '!' is not allowed outside quotes)"

This means the format of your config file is incorrect, I'm taking a guess at the rules list portion.
it should look something like this: 
![image](https://cloud.githubusercontent.com/assets/3026728/23634416/07abfacc-02c2-11e7-855b-0d46019f1f0d.png)

If you don't know how to format it correctly i could do it for you.

**Comment by FirEmerald** [comment]
I just noticed that looking through the log myself

**Comment by FirEmerald** [comment]
Should probably figure out why that causes the commands to not work - failsafes are your friend and could save from this happening again

**Comment by leelawd** [comment]
The config caused the plugin to fail to load completely, but your correct. i should put in a check for that. It was an oversight while creating it.
