### ISSUE TITLE
Plugin does not work on sponge api 7

### ISSUE THREAD

**Issue by ghost** [ModdedMinecraft/MMCRules-Sponge#3]
Could you update this plugin for Sponge api 7?

**Comment by leelawd** [comment]
Is there any errors that come up when attempting to load this on api7 or anything that specifically doesn't work properly?

**Comment by ghost** [comment]
Sorry it took so long, got caught up with work but here's the error https://gist.github.com/xKnightGamingx/77280648e8723e22b6e1ea067a447558

**Comment by leelawd** [comment]
Alright, after some research I believe this issue is related to a change with the SpongeAPI https://github.com/SpongePowered/SpongeAPI/commit/c4ead797895918d375855bb6124bc34786e00839

I have tried to get around this but it seems that this issue will need to be addressed by them.

**Comment by leelawd** [comment]
I do not believe that this is an issue any more.
